name: Node.js CI

on:
  push:
    branches: [master, develop]
  pull_request:

jobs:
  test-node:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version: [16.x]

    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies (and link per package)
        run: npm ci

      - name: Install hedera-local node globally
        run: npm install -g @hashgraph/hedera-local

      - name: Build CommonJS and ESM (from TypeScript)
        run: npm run build-all

      - name: Run tests
        run: npm run test-node

  coverage:
    name: Coverage

    runs-on: ubuntu-latest

    continue-on-error: true

    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies (and link per package)
        run: npm ci

      - name: Install hedera-local node globally
        run: npm install -g https://github.com/hashgraph/hedera-local-node.git#v.1.1.0

      - name: Build CommonJS and ESM (from TypeScript)
        run: npm run build-all

      - name: Run tests
        run: npm run test-coverage

      - name: Upload coverage summary
        uses: actions/upload-artifact@v2
        with:
          name: coverage-summary
          path: ./output/summary.txt

      - name: Tar files
        run: tar -cvf ./output/coverage.tar ./output/lcov-report/

      - name: Upload coverage
        uses: actions/upload-artifact@v2
        with:
          name: coverage-complete
          path: ./output/coverage.tar
